### ISSUE TITLE
Amazon Aurora paper link is broken

### ISSUE THREAD

**Issue by naitikmalaviya** [InterviewReady/system-design-resources#25]
[Amazon Aurora paper link](https://web.stanford.edu/class/cs245/readings/aurora.pdf) on [White papers that are worth your time](https://interviewready.io/blog/white-papers-worth-reading-for-software-engineers) page is broken. It throws Access forbidden error.

[Working link.](https://assets.amazon.science/dc/2b/4ef2b89649f9a393d37d3e042f4e/amazon-aurora-design-considerations-for-high-throughput-cloud-native-relational-databases.pdf)

source: [amazon | science](https://www.amazon.science/publications/amazon-aurora-design-considerations-for-high-throughput-cloud-native-relational-databases)

**Comment by coding-parrot** [comment]
Thanks for reporting, it's fixed now :D
